### PR TITLE
Add Flask-WhooshAlchemy3

### PR DESCRIPTION
**Pull request by deb17**
Thought that this extension should be added after watching a video by Pretty Printed - https://www.youtube.com/watch?v=bAPcmGNsulc .

### CODE REVIEW

**Comment by mjhea0** [comment]
@deb17 thanks for the PR. Are you sure that extension is still being maintained? It looks like it there hasn't been a release in about 6 years.

**Comment by deb17** [comment]
You are right. The last release was in 2014. But I found on pypi - flask-whooshalchemy3 which is inspired by the original and is recent. Maybe that should figure in your list?

**Comment by mjhea0** [comment]
Yes, that looks good. Want to update the PR?

**Comment by deb17** [comment]
I have updated the file. Thanks.

**Comment by deb17** [comment]
Did I miss something? It's my first PR!

**Pull request merged**
